// ============================================
// Setup Wizard — Interactive first-time config
// ============================================
import inquirer from 'inquirer';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT_DIR = path.resolve(__dirname, '..');

console.log('');
console.log('╔═══════════════════════════════════════════════════╗');
console.log('║        🔧 JOB SCRAPER — SETUP WIZARD             ║');
console.log('╚═══════════════════════════════════════════════════╝');
console.log('');

async function runSetup() {
    // ── Step 1: API Keys ────────────────────────────
    console.log('━━━ Step 1/4: API Keys ━━━━━━━━━━━━━━━━━━━━━━━━━━━');
    console.log('');

    const apiAnswers = await inquirer.prompt([
        {
            type: 'input',
            name: 'apifyToken',
            message: 'Apify API Token (from https://console.apify.com/account/integrations):',
            validate: (input) => input.length > 5 ? true : 'Please enter a valid Apify API token',
        },
        {
            type: 'input',
            name: 'openaiKey',
            message: 'OpenAI API Key (from https://platform.openai.com/api-keys):',
            validate: (input) => input.startsWith('sk-') ? true : 'OpenAI keys start with "sk-"',
        },
        {
            type: 'list',
            name: 'openaiModel',
            message: 'OpenAI model to use:',
            choices: [
                { name: 'GPT-4o-mini (Cheapest, recommended)', value: 'gpt-4o-mini' },
                { name: 'GPT-4o (Best quality, more expensive)', value: 'gpt-4o' },
                { name: 'GPT-3.5-turbo (Legacy, cheapest)', value: 'gpt-3.5-turbo' },
            ],
            default: 'gpt-4o-mini',
        },
    ]);

    // ── Step 2: Job Search Parameters ───────────────
    console.log('');
    console.log('━━━ Step 2/4: Job Search Parameters ━━━━━━━━━━━━━━');
    console.log('');

    const searchAnswers = await inquirer.prompt([
        {
            type: 'input',
            name: 'keywords',
            message: 'Job search keywords (e.g., "Full Stack Developer"):',
            default: 'Full Stack Developer',
        },
        {
            type: 'input',
            name: 'location',
            message: 'Location (e.g., "Chennai, India" or "Remote"):',
            default: 'India',
        },
        {
            type: 'number',
            name: 'maxJobsPerSite',
            message: 'Max jobs to fetch per site:',
            default: 20,
        },
    ]);

    // ── Step 3: Enable/Disable Sites ────────────────
    console.log('');
    console.log('━━━ Step 3/4: Job Sites ━━━━━━━━━━━━━━━━━━━━━━━━━━');
    console.log('');

    const siteAnswers = await inquirer.prompt([
        {
            type: 'checkbox',
            name: 'enabledSites',
            message: 'Select job sites to scrape:',
            choices: [
                { name: 'LinkedIn', value: 'LinkedIn', checked: true },
                { name: 'Indeed', value: 'Indeed', checked: true },
                { name: 'Glassdoor', value: 'Glassdoor', checked: true },
                { name: 'Naukri', value: 'Naukri', checked: true },
                { name: 'RemoteOK', value: 'RemoteOK', checked: true },
            ],
            validate: (input) => input.length > 0 ? true : 'Select at least one site',
        },
    ]);

    // ── Step 4: Schedule ────────────────────────────
    console.log('');
    console.log('━━━ Step 4/4: Schedule ━━━━━━━━━━━━━━━━━━━━━━━━━━━');
    console.log('');

    const scheduleAnswers = await inquirer.prompt([
        {
            type: 'list',
            name: 'schedule',
            message: 'When should the scraper run daily?',
            choices: [
                { name: '9:00 AM (recommended)', value: '0 9 * * *' },
                { name: '8:00 AM', value: '0 8 * * *' },
                { name: '10:00 AM', value: '0 10 * * *' },
                { name: '7:00 AM', value: '0 7 * * *' },
                { name: '12:00 PM', value: '0 12 * * *' },
            ],
            default: '0 9 * * *',
        },
        {
            type: 'confirm',
            name: 'notifications',
            message: 'Enable desktop notifications?',
            default: true,
        },
    ]);

    // ── Generate .env File ──────────────────────────
    console.log('');
    console.log('━━━ Generating configuration files... ━━━━━━━━━━━━');

    const envContent = `# ============================================
# Job Scraper — Environment Configuration
# Generated by setup wizard on ${new Date().toLocaleString('en-IN')}
# ============================================

# Apify API Token
APIFY_API_TOKEN=${apiAnswers.apifyToken}

# OpenAI API Key
OPENAI_API_KEY=${apiAnswers.openaiKey}

# OpenAI Model
OPENAI_MODEL=${apiAnswers.openaiModel}

# Schedule (cron expression)
SCHEDULE_CRON=${scheduleAnswers.schedule}

# Timezone
TIMEZONE=Asia/Kolkata

# Max jobs per site
MAX_JOBS_PER_SITE=${searchAnswers.maxJobsPerSite}

# Job age filter (hours)
JOB_AGE_HOURS=24

# Output directory
OUTPUT_DIR=./output

# Log level
LOG_LEVEL=info

# Desktop notifications
NOTIFICATIONS_ENABLED=${scheduleAnswers.notifications}
`;

    fs.writeFileSync(path.join(ROOT_DIR, '.env'), envContent);
    console.log('   ✅ .env file created');

    // ── Update sites.json with search params ────────
    const sitesPath = path.join(ROOT_DIR, 'config', 'sites.json');
    if (fs.existsSync(sitesPath)) {
        const sites = JSON.parse(fs.readFileSync(sitesPath, 'utf-8'));
        for (const site of sites) {
            site.enabled = siteAnswers.enabledSites.includes(site.name);
            site.searchParams.keywords = searchAnswers.keywords;
            site.searchParams.location = searchAnswers.location;
            site.searchParams.maxItems = searchAnswers.maxJobsPerSite;
        }
        fs.writeFileSync(sitesPath, JSON.stringify(sites, null, 2));
        console.log('   ✅ config/sites.json updated');
    }

    // ── Ensure directories exist ────────────────────
    const dirs = ['resume', 'output', 'logs'];
    for (const dir of dirs) {
        const dirPath = path.join(ROOT_DIR, dir);
        if (!fs.existsSync(dirPath)) {
            fs.mkdirSync(dirPath, { recursive: true });
        }
    }
    console.log('   ✅ Directories created (resume/, output/, logs/)');

    // ── Final Instructions ──────────────────────────
    console.log('');
    console.log('╔═══════════════════════════════════════════════════╗');
    console.log('║           ✅ SETUP COMPLETE!                      ║');
    console.log('╠═══════════════════════════════════════════════════╣');
    console.log('║                                                   ║');
    console.log('║  Next steps:                                      ║');
    console.log('║                                                   ║');
    console.log('║  1. Place your resume.pdf in the "resume/" folder ║');
    console.log('║                                                   ║');
    console.log('║  2. Run once to test:                             ║');
    console.log('║     npm run run                                   ║');
    console.log('║                                                   ║');
    console.log('║  3. Start the daily scheduler:                    ║');
    console.log('║     npm start                                     ║');
    console.log('║                                                   ║');
    console.log('╚═══════════════════════════════════════════════════╝');
    console.log('');
}

runSetup().catch(error => {
    console.error('❌ Setup failed:', error.message);
    process.exit(1);
});
